# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs mount
      - name: mount tmpfs as /tmp
        mount: name=/ramdisk src='tmpfs' fstype=tmpfs opts='size=1m' state=mounted
      # Runs a set of commands using the runners shell
      - name: Copy script to RAM disk and run script
        run: cp -prP roundswarm /ramdisk/. && bash -x /ramdisk/roundswarm
